package sistema.controller;
// Generated 05/06/2017 10:05:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Embeddable;
import javax.persistence.Embedded;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Cadastro generated by hbm2java
 */
@Embeddable
public class Cadastro  implements java.io.Serializable {

     @Id @GeneratedValue
     private Integer idCadastro;
     @Embedded
     private Endereco endereco;
     @Embedded
     private Telefone telefone;
     private String nome;
     private String rg;
     private String cpf;
     private Date dataNascimento;
     private String email;
     private Set funcionarioTecnicos = new HashSet(0);
     private Set clientes = new HashSet(0);

    public Cadastro() {
    }

	
    public Cadastro(Endereco endereco, Telefone telefone, String nome, String rg, String cpf, Date dataNascimento, String email) {
        this.endereco = endereco;
        this.telefone = telefone;
        this.nome = nome;
        this.rg = rg;
        this.cpf = cpf;
        this.dataNascimento = dataNascimento;
        this.email = email;
    }
    public Cadastro(Endereco endereco, Telefone telefone, String nome, String rg, String cpf, Date dataNascimento, String email, Set funcionarioTecnicos, Set clientes) {
       this.endereco = endereco;
       this.telefone = telefone;
       this.nome = nome;
       this.rg = rg;
       this.cpf = cpf;
       this.dataNascimento = dataNascimento;
       this.email = email;
       this.funcionarioTecnicos = funcionarioTecnicos;
       this.clientes = clientes;
    }
   
    public Integer getIdCadastro() {
        return this.idCadastro;
    }
    
    public void setIdCadastro(Integer idCadastro) {
        this.idCadastro = idCadastro;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public Telefone getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Telefone telefone) {
        this.telefone = telefone;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getFuncionarioTecnicos() {
        return this.funcionarioTecnicos;
    }
    
    public void setFuncionarioTecnicos(Set funcionarioTecnicos) {
        this.funcionarioTecnicos = funcionarioTecnicos;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }

}


