package sistema.controller;
// Generated 05/06/2017 10:05:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name="Fornecedor")
public class Fornecedor  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy=GenerationType.IDENTITY)
     private int idFornecedor;
     private Endereco endereco;
     private Telefone telefone;
     private String nome;
     private Set produtos = new HashSet(0);

    public Fornecedor() {
    }

	
    public Fornecedor(int idFornecedor, Endereco endereco, Telefone telefone) {
        this.idFornecedor = idFornecedor;
        this.endereco = endereco;
        this.telefone = telefone;
    }
    public Fornecedor(int idFornecedor, Endereco endereco, Telefone telefone, String nome, Set produtos) {
       this.idFornecedor = idFornecedor;
       this.endereco = endereco;
       this.telefone = telefone;
       this.nome = nome;
       this.produtos = produtos;
    }
   
    public int getIdFornecedor() {
        return this.idFornecedor;
    }
    
    public void setIdFornecedor(int idFornecedor) {
        this.idFornecedor = idFornecedor;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public Telefone getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Telefone telefone) {
        this.telefone = telefone;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


