package sistema.controller;
// Generated 05/06/2017 10:05:02 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import sistema.model.DAOPragasEncontradas;




/**
 * PragasEncontradas generated by hbm2java
 */
@Entity
@Table(name="PragasEncontradas")
public class PragasEncontradas  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy=GenerationType.IDENTITY)
     private int idPragasEncontradas;
     private OrdemServico ordemServico;
     private Pragas pragas;
     private Integer quantidade;

    public PragasEncontradas() {
    }

	
    public PragasEncontradas(int idPragasEncontradas, OrdemServico ordemServico, Pragas pragas) {
        this.idPragasEncontradas = idPragasEncontradas;
        this.ordemServico = ordemServico;
        this.pragas = pragas;
    }
    public PragasEncontradas(int idPragasEncontradas, OrdemServico ordemServico, Pragas pragas, Integer quantidade) {
       this.idPragasEncontradas = idPragasEncontradas;
       this.ordemServico = ordemServico;
       this.pragas = pragas;
       this.quantidade = quantidade;
    }
   
    public int getIdPragasEncontradas() {
        return this.idPragasEncontradas;
    }
    
    public void setIdPragasEncontradas(int idPragasEncontradas) {
        this.idPragasEncontradas = idPragasEncontradas;
    }
    public OrdemServico getOrdemServico() {
        return this.ordemServico;
    }
    
    public void setOrdemServico(OrdemServico ordemServico) {
        this.ordemServico = ordemServico;
    }
    public Pragas getPragas() {
        return this.pragas;
    }
    
    public void setPragas(Pragas pragas) {
        this.pragas = pragas;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }

    public void armazenar(){
        DAOPragasEncontradas pe = new DAOPragasEncontradas();
        pe.armazenar(this);
        
        
    }


}


