package sistema.controller;
// Generated 05/06/2017 10:05:02 by Hibernate Tools 4.3.1


import sistema.model.DAOPragas;
import sistema.model.DAOUsuario;
import java.util.HashSet;
import java.util.Set;

/**
 * Pragas generated by hbm2java
 */
public class Pragas  implements java.io.Serializable {


     private int idPragas;
     private String nome;
     private Set pragasEncontradases = new HashSet(0);

    public Pragas() {
    }

	
    public Pragas(int idPragas) {
        this.idPragas = idPragas;
    }
    public Pragas(int idPragas, String nome, Set pragasEncontradases) {
       this.idPragas = idPragas;
       this.nome = nome;
       this.pragasEncontradases = pragasEncontradases;
    }
   
    public int getIdPragas() {
        return this.idPragas;
    }
    
    public void setIdPragas(int idPragas) {
        this.idPragas = idPragas;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getPragasEncontradases() {
        return this.pragasEncontradases;
    }
    
    public void setPragasEncontradases(Set pragasEncontradases) {
        this.pragasEncontradases = pragasEncontradases;
    }

    public void alterar(){
        DAOPragas dAOPraga = new DAOPragas();
        dAOPraga.alterar(this);
    }
    
    public void excluir(){
        DAOPragas dAOPraga = new DAOPragas();
        dAOPraga.excluir(this.getIdPragas());
    }
    
    public void armazenar(){
        DAOPragas dAOPraga = new DAOPragas();
        dAOPraga.armazenar(this);
    }
}


