package sistema.controller;
// Generated 05/06/2017 10:05:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import sistema.model.DAOProduto;

/**
 * Produto generated by hbm2java
 */
@Embeddable
@Table(name="Produto")
public class Produto  implements java.io.Serializable{
@Id
@GeneratedValue(strategy=GenerationType.IDENTITY)

     private int idProduto;
     private Fornecedor fornecedor;
     private String nome;
     private String principioAtivo;
     private String fabricante;
     private Float preco;
     private Integer quantidadeEstoque;
     private Set produtoServicos = new HashSet(0);

    public Produto() {
    }
    
    public Produto(int idProduto, Fornecedor fornecedor) {
        this.idProduto = idProduto;
        this.fornecedor = fornecedor;
    }
    public Produto(int idProduto, Fornecedor fornecedor, String nome, String principioAtivo, String fabricante, Float preco, Integer quantidadeEstoque, Set produtoServicos) {
       this.idProduto = idProduto;
       this.fornecedor = fornecedor;
       this.nome = nome;
       this.principioAtivo = principioAtivo;
       this.fabricante = fabricante;
       this.preco = preco;
       this.quantidadeEstoque = quantidadeEstoque;
       this.produtoServicos = produtoServicos;
    }
   
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getPrincipioAtivo() {
        return this.principioAtivo;
    }
    
    public void setPrincipioAtivo(String principioAtivo) {
        this.principioAtivo = principioAtivo;
    }
    public String getFabricante() {
        return this.fabricante;
    }
    
    public void setFabricante(String fabricante) {
        this.fabricante = fabricante;
    }
    public Float getPreco() {
        return this.preco;
    }
    
    public void setPreco(Float preco) {
        this.preco = preco;
    }
    public Integer getQuantidadeEstoque() {
        return this.quantidadeEstoque;
    }
    
    public void setQuantidadeEstoque(Integer quantidadeEstoque) {
        this.quantidadeEstoque = quantidadeEstoque;
    }
    public Set getProdutoServicos() {
        return this.produtoServicos;
    }
    
    public void setProdutoServicos(Set produtoServicos) {
        this.produtoServicos = produtoServicos;
    }

    public void alterar(){
        DAOProduto dao = new DAOProduto();
        dao.alterar(this);
    }


}


