package sistema.controller;
// Generated 05/06/2017 10:05:02 by Hibernate Tools 4.3.1

import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import sistema.model.DAOProposta;




/**
 * Proposta generated by hbm2java
 */
@Embeddable
@Table(name="Proposta")
public class Proposta  implements java.io.Serializable {
@Id
@GeneratedValue(strategy=GenerationType.IDENTITY)

    private static final String ESPORADICO = "I";
    
    private int idProposta;
    private Cliente cliente;
    private String tipoServico, tipoServicoExtenso;
    private Float orcamento;
    private String descricao;
    private String status, statusExtenso;

    public Proposta() {
    }

	
    public Proposta(int idProposta, Cliente cliente, String descricao) {
        this.idProposta = idProposta;
        this.cliente = cliente;
        this.descricao = descricao;
    }
    public Proposta(int idProposta, Cliente cliente, String tipoServico, Float orcamento, String descricao, String status) {
       this.idProposta = idProposta;
       this.cliente = cliente;
       this.tipoServico = tipoServico.equals(ESPORADICO) ? "Esporádico" : "Periódico";
       this.tipoServicoExtenso = tipoServico.equals(ESPORADICO) ? "Esporádico" : "Periódico";
       this.orcamento = orcamento;
       this.descricao = descricao;
       this.status = status;
       if(status.equals("A")){
           this.statusExtenso = "Aprovada";
       }else if(status.equals("R")){
           this.statusExtenso = "Reprovada";
       }else if(status.equals("P")){
           this.statusExtenso = "Pendente";
       }
    }
   
    public int getIdProposta() {
        return this.idProposta;
    }
    
    public void atualizarAttrs(){
        this.tipoServicoExtenso = tipoServico.equals(ESPORADICO) ? "Esporádico" : "Periódico";
        if(status.equals("A")){
           this.statusExtenso = "Aprovada";
       }else if(status.equals("R")){
           this.statusExtenso = "Reprovada";
       }else if(status.equals("P")){
           this.statusExtenso = "Pendente";
       }
    }
    
    public void setIdProposta(int idProposta) {
        this.idProposta = idProposta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getTipoServico() {
        return this.tipoServico;
    }
    
    public void setTipoServico(String tipoServico) {
        this.tipoServico = tipoServico;
    }

    public String getTipoServicoExtenso() {
        return tipoServicoExtenso;
    }

    public void setTipoServicoExtenso(String tipoServicoExtenso) {
        this.tipoServicoExtenso = tipoServicoExtenso;
    }

    public String getStatusExtenso() {
        return statusExtenso;
    }

    public void setStatusExtenso(String statusExtenso) {
        this.statusExtenso = statusExtenso;
    }
    
    
    
    public String getTipoServicoEnum(){
        return String.valueOf(tipoServico.charAt(0));
    }
    
    public Float getOrcamento() {
        return this.orcamento;
    }
    
    public void setOrcamento(Float orcamento) {
        this.orcamento = orcamento;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public void armazenar(){
        DAOProposta dao = new DAOProposta();
        dao.armazenar(this);
    }
    
    public void buscar(){
        DAOProposta dao = new DAOProposta();
        dao.buscarComID(this.idProposta);
    }
    
    public void alterar(){
        DAOProposta dao = new DAOProposta();
        dao.alterar(this);
    }
}


