package sistema.controller;
// Generated 05/06/2017 10:05:02 by Hibernate Tools 4.3.1

import sistema.model.DAOUsuario;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * Usuario generated by hbm2java
 */
@Embeddable
@Table(name="Usuario")
public class Usuario  implements java.io.Serializable {
     @Id
     @GeneratedValue(strategy=GenerationType.IDENTITY)
     private Integer idUsuario;
     private String login;
     private String senha;
     private String tipo;

    public Usuario() {
    }

    public Usuario(String login, String senha, String tipo) {
       this.login = login;
       this.senha = senha;
       this.tipo = tipo;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public Usuario logar(){
        DAOUsuario dAOUsuario = new DAOUsuario();
        Usuario usuario = dAOUsuario.Autenticar(this.login, this.senha);
        return usuario;
    }
    
    public void armazenar(){
        DAOUsuario dAOUsuario = new DAOUsuario();
        dAOUsuario.armazenar(this);
    }
    
    public void alterar(){
        DAOUsuario dAOUsuario = new DAOUsuario();
        dAOUsuario.alterar(this);
    }
    
    public void excluir(int idLogado){
        DAOUsuario dAOUsuario = new DAOUsuario();
        dAOUsuario.excluir(this, idLogado);
    }
}


