/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.view;

import java.util.StringTokenizer;
import sistema.model.DAOFornecedor;
import sistema.controller.Endereco;
import sistema.controller.Fornecedor;
import sistema.controller.Telefone;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistema.model.DAOEndereco;

/**
 *
 * @author rafael
 */
public class FornecedorGUI extends javax.swing.JInternalFrame {
    private Fornecedor fornecedor;
    /**
     * Creates new form CrudCliente
     */
    public FornecedorGUI() {
        initComponents();
        atualizarTabelaFornecedor();
        desativarBotoes();
        this.btnSave.setEnabled(true);
        carregarEnd();
    }
    
    void carregarEnd(){
        this.jEnd.removeAllItems();
        DAOEndereco end = new DAOEndereco();
        end.listar(this.jEnd);
    }
    
    private void limpaCampos(){
        txtNome.setText("");
        txtFixo.setText("");
        txtCelDD.setText("");
        txtFixoDD.setText("");
        txtCel.setText("");
    }
    
    private void ativarBotoes(){
        this.btnDelete.setEnabled(true);
        this.btnMerge.setEnabled(true);
        this.btnSave.setEnabled(true);
    }
    
    private void desativarBotoes(){
        this.btnDelete.setEnabled(false);
        this.btnMerge.setEnabled(false);
        this.btnSave.setEnabled(false);
    }
    
    private boolean verificaCampos(){
        boolean nome = false, end = false, fone = false;
        if(!txtNome.getText().isEmpty()){
            nome = true;
        }
        /*if(!txtEnd.getText().isEmpty()){
            end = true;
        }
        if(!txtEnd.getText().isEmpty()){
            fone = true;
        }*/
        return nome;
    }
    
    private void setFornecedor(int idFornecedor){
        DAOFornecedor dAOFornecedor = new DAOFornecedor();
        this.fornecedor = dAOFornecedor.buscarComID(idFornecedor);
        
        txtNome.setText(this.fornecedor.getNome());
        
        txtCelDD.setText(this.fornecedor.getTelefone().getTelCelular().substring(0, 2));
        txtCel.setText(this.fornecedor.getTelefone().getTelCelular().substring(2));
        txtFixoDD.setText(this.fornecedor.getTelefone().getTelFixo().substring(0, 2));
        txtFixo.setText(this.fornecedor.getTelefone().getTelFixo().substring(2));
        
        int idEnd = this.fornecedor.getEndereco().getIdEndereco();
        for(int i = 0; i < jEnd.getItemCount(); i++){
            StringTokenizer aux = new StringTokenizer(jEnd.getItemAt(i), " ");
            int idScroll = Integer.parseInt(aux.nextToken());
            if(idScroll == idEnd){
                jEnd.setSelectedIndex(i);
                break;
            }
        }
        
    }
    
    private void atualizarTabelaFornecedor()
    {
        limparTabela();
        DAOFornecedor dAOFornecedor = new DAOFornecedor();
        DefaultTableModel modelo = (DefaultTableModel) tblFornecedores.getModel();
        dAOFornecedor.listar(modelo);
    }
    
    
    public void limparTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tblFornecedores.getModel();
        modelo.setNumRows(0);
        tblFornecedores.setModel(modelo);
    }
    
    private void PesquisarFornecedores(){
        DAOFornecedor dAOFornecedor = new DAOFornecedor();
        DefaultTableModel modelo = (DefaultTableModel) tblFornecedores.getModel();
        dAOFornecedor.listarComLike(BarraDeBusca.getText(), modelo);
    }
    
    private Fornecedor criarFornecedor(){
        Fornecedor f = new Fornecedor();
        Endereco endereco = new Endereco();
        Telefone telefone = new Telefone();
        f.setNome(txtNome.getText());
        StringTokenizer aux = new StringTokenizer(jEnd.getSelectedItem().toString(), " ");
        endereco.buscarComId(Integer.parseInt(aux.nextToken()));
        
        String num = txtCelDD.getText()+txtCel.getText();
        telefone.setTelCelular(num);
        num = txtFixoDD.getText()+txtFixo.getText();
        telefone.setTelFixo(num);
        
        f.setEndereco(endereco);
        f.setTelefone(telefone);
        
        
        return f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        txtEnd1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFornecedores = new javax.swing.JTable();
        BarraDeBusca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnMerge = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFixoDD = new javax.swing.JTextField();
        txtFixo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCelDD = new javax.swing.JTextField();
        txtCel = new javax.swing.JTextField();
        jEnd = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Informações de Endereço");

        jTextField9.setText("jTextField8");

        jLabel8.setText("Endereco");

        setPreferredSize(new java.awt.Dimension(1050, 550));

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fornecedores");

        tblFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblFornecedoresMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblFornecedores);

        BarraDeBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BarraDeBuscaKeyReleased(evt);
            }
        });

        jLabel2.setText("Nome do Fornecedor");

        btnMerge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Compose_2190985.png"))); // NOI18N
        btnMerge.setText("Alterar");
        btnMerge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMergeActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Close_2190987.png"))); // NOI18N
        btnDelete.setText("Excluir");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Plus_2190977.png"))); // NOI18N
        btnSave.setText("Adicionar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMerge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnMerge)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("*Nome");

        jLabel11.setText("*Telefone Fixo");

        jLabel12.setText("*Telefone Cel");

        jEnd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("*Endereço");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jEnd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(txtFixoDD, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(txtCelDD, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCel)))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFixoDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BarraDeBusca))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BarraDeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(63, 63, 63)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMergeActionPerformed
        // TODO add your handling code here:
        DAOFornecedor dAOFornecedor = new DAOFornecedor();
        Fornecedor f = criarFornecedor();
        f.setIdFornecedor(this.fornecedor.getIdFornecedor());
        dAOFornecedor.alterar(f);
        
        limpaCampos();
        atualizarTabelaFornecedor();
        this.fornecedor = null;
        this.btnDelete.setEnabled(false);
        this.btnMerge.setEnabled(false);
    }//GEN-LAST:event_btnMergeActionPerformed

    private void tblFornecedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFornecedoresMousePressed
        // TODO add your handling code here:
        int linhaTabelaForn = tblFornecedores.getSelectedRow();
        String id = tblFornecedores.getModel().getValueAt(linhaTabelaForn, 0).toString();
        this.fornecedor = new Fornecedor();
        this.fornecedor.setIdFornecedor(Integer.parseInt(id));
        setFornecedor(Integer.parseInt(id));
        this.ativarBotoes();
    }//GEN-LAST:event_tblFornecedoresMousePressed

    private void BarraDeBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BarraDeBuscaKeyReleased
        // TODOtblFornecedoresandling code here:
        limparTabela();
        PesquisarFornecedores();
    }//GEN-LAST:event_BarraDeBuscaKeyReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DAOFornecedor dAOFornecedor = new DAOFornecedor();
        dAOFornecedor.excluir(this.fornecedor.getIdFornecedor());
        this.limparTabela();
        atualizarTabelaFornecedor();
        this.fornecedor = null;
        limpaCampos();
        this.btnDelete.setEnabled(false);
        this.btnMerge.setEnabled(false);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        DAOFornecedor dAOFornecedor = new DAOFornecedor();
        if(verificaCampos()){
            Fornecedor f = criarFornecedor();
            dAOFornecedor.armazenar(f);
        }else{
            JOptionPane.showMessageDialog(null, "Campo(s) obrigatório(s) em branco.");
        }
        
        limpaCampos();
        this.fornecedor = null;
        this.btnDelete.setEnabled(false);
        this.btnMerge.setEnabled(false);
        atualizarTabelaFornecedor();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraDeBusca;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMerge;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> jEnd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable tblFornecedores;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtCelDD;
    private javax.swing.JTextField txtEnd1;
    private javax.swing.JTextField txtFixo;
    private javax.swing.JTextField txtFixoDD;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
