/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.view;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.StringTokenizer;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import sistema.controller.Cliente;
import sistema.controller.OrdemServico;
import sistema.controller.Pragas;
import sistema.controller.PragasEncontradas;
import sistema.controller.Produto;
import sistema.controller.ProdutoServico;
import sistema.controller.Proposta;
import sistema.controller.Usuario;
import sistema.model.DAOCliente;
import sistema.model.DAOPragas;
import sistema.model.DAOProduto;
import sistema.model.DAOProposta;
import sistema.model.DAOServico;

/**
 *
 * @author thais
 */
public class PrincipalGUI extends javax.swing.JInternalFrame {
    Usuario usuarioLogado;
    int linhaTabelaProposta;
    int linhaTabelaServico;
    /**
     * Creates new form Principal
     */
    public PrincipalGUI(Usuario usuario) {
        initComponents();
        this.usuarioLogado = usuario;
        atualizarTabelaProposta();
        desativarBotoesProposta();
        desativarBotoesServ();
        atualizarTabelaServico();
    }
   
    private void desativarBotoesProposta(){
        this.btnCancelar.setEnabled(false);
        this.btnConcluido.setEnabled(false);
        this.btnGerarOrdens.setEnabled(false);
    }
    
    private void desativarBotoesServ(){
        this.btnCancelar.setEnabled(false);
        this.btnConcluido.setEnabled(false);
        this.btnAgendar.setEnabled(false);
    }
    
    private void atualizarTabelaProposta(){
        limparTabelaProp();
        DAOProposta daoProposta = new DAOProposta();
        DefaultTableModel modelo = (DefaultTableModel) tblProposta.getModel();
        daoProposta.listarComJoinClienteCPF("status", "A", modelo);
    }
    
    private void atualizarTabelaServico(){
        limparTabelaServ();
        DAOServico daoServico = new DAOServico();
        DefaultTableModel modelo = (DefaultTableModel) tblServico.getModel();
        daoServico.listarComLike("status", "A",modelo);
        daoServico.listarComLike("status", "P",modelo);
    }
    
    public void limparTabelaProp(){
        DefaultTableModel modelo = (DefaultTableModel) tblProposta.getModel();
        modelo.setNumRows(0);
        tblProposta.setModel(modelo);
    }
    
    public void limparTabelaServ(){
        DefaultTableModel modelo = (DefaultTableModel) tblServico.getModel();
        modelo.setNumRows(0);
        tblServico.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar1 = new javax.swing.JToggleButton();
        btnConcluido1 = new javax.swing.JToggleButton();
        btnEndeGroup = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServico = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProposta = new javax.swing.JTable();
        btnGerarOrdens = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();
        btnConcluido = new javax.swing.JToggleButton();
        btnAgendar = new javax.swing.JButton();
        jDate = new com.toedter.calendar.JDateChooser();

        btnCancelar1.setText("Cancelar");

        btnConcluido1.setText("Concluído");

        setPreferredSize(new java.awt.Dimension(1050, 550));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Serviços");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Propostas");

        tblServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Status", "Preco (R$)", "Cliente", "Endereço", "Data", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblServicoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblServico);

        tblProposta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CPF", "Descrição", "Orçamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProposta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPropostaMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblProposta);

        btnGerarOrdens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Settings_2190975.png"))); // NOI18N
        btnGerarOrdens.setText("Gerar Ordens");
        btnGerarOrdens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarOrdensActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Close_2190987.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnConcluido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Checkmark_2190986.png"))); // NOI18N
        btnConcluido.setText("Concluído");
        btnConcluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluidoActionPerformed(evt);
            }
        });

        btnAgendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pcalendar.png"))); // NOI18N
        btnAgendar.setText("Agendar");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGerarOrdens)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgendar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConcluido))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConcluido)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGerarOrdens)
                        .addComponent(btnAgendar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPropostaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPropostaMousePressed
        // TODO add your handling code here:
        linhaTabelaProposta = tblProposta.getSelectedRow();
        this.btnGerarOrdens.setEnabled(true);
        this.desativarBotoesServ();
    }//GEN-LAST:event_tblPropostaMousePressed

    private void btnGerarOrdensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarOrdensActionPerformed
        // TODO add your handling code here:
        DAOCliente dAOcliente = new DAOCliente();
        Cliente c;
        OrdemServico s;
        SpinnerNumberModel sModel = new SpinnerNumberModel(0, 0, 30, 1);
        JSpinner spinner = new JSpinner(sModel);
        spinner.setValue(1);
        String desc = JOptionPane.showInputDialog(null, spinner, "descrição");
        int qtd = (int) spinner.getValue();
        String cpf = tblProposta.getModel().getValueAt(linhaTabelaProposta, 1).toString();
        float preco = Float.parseFloat(tblProposta.getModel().getValueAt(linhaTabelaProposta, 3).toString());
        preco /= qtd;
        c = dAOcliente.buscarComCPF(cpf);
        while(qtd > 0){
            s = new OrdemServico();
            s.setCliente(c);
            s.setPrecoTotal(preco);
            s.setEndereco(c.getCadastro().getEndereco());
            s.setDescricao(desc);
            s.setStatus("P");
            s.armazenar();
            qtd--;
        }
        DAOProposta dao = new DAOProposta();
        Proposta p = dao.buscarComID(Integer.parseInt(tblProposta.getModel().getValueAt(linhaTabelaProposta, 0).toString()));
        if(p.getTipoServico().equals("P")){
            p.setStatus("P");
            p.alterar();
        }else{
            dao.excluir(Integer.parseInt(tblProposta.getModel().getValueAt(linhaTabelaProposta, 0).toString()));
        }
        atualizarTabelaProposta();
        atualizarTabelaServico();
        this.btnGerarOrdens.setEnabled(false);
    }//GEN-LAST:event_btnGerarOrdensActionPerformed

    private void tblServicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServicoMousePressed
        // TODO add your handling code here:
        linhaTabelaServico = tblServico.getSelectedRow();
        desativarBotoesProposta();
        desativarBotoesServ();
        String status = tblServico.getModel().getValueAt(linhaTabelaServico, 1).toString();
        if(status.equals("A")){
            this.btnCancelar.setEnabled(true);
            this.btnConcluido.setEnabled(true);
        }else {
            this.btnAgendar.setEnabled(true);
            this.btnCancelar.setEnabled(true);
        }
    }//GEN-LAST:event_tblServicoMousePressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        String id = tblServico.getModel().getValueAt(linhaTabelaServico, 0).toString();
        OrdemServico os;
        DAOServico dao = new DAOServico();
        os = dao.buscarComID(Integer.parseInt(id));
        os.excluir();
        atualizarTabelaServico();
        this.desativarBotoesServ();
    }//GEN-LAST:event_btnCancelarActionPerformed
    
   
    
    private void btnConcluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluidoActionPerformed
        // TODO add your handling code here:
        String id = tblServico.getModel().getValueAt(linhaTabelaServico, 0).toString();
        OrdemServico os;
        DAOServico dao = new DAOServico();
        os = dao.buscarComID(Integer.parseInt(id));
        os.setStatus("C");
        
        JComboBox sModel = new JComboBox();
        sModel.removeAllItems();
        DAOPragas p = new DAOPragas();
        p.listar(sModel);
        
        String pragas = JOptionPane.showInputDialog(null, sModel , "Tipo e quantidade de pragas encontradas", JOptionPane.OK_OPTION);
        
        JComboBox pModel = new JComboBox();
        pModel.removeAllItems();
        DAOProduto pd = new DAOProduto();
        pd.listar(pModel);
        
        String prod = JOptionPane.showInputDialog(null, pModel,"Tipo e quantidade de produto usado", JOptionPane.OK_OPTION);
        
        PragasEncontradas pe = new PragasEncontradas();
        ProdutoServico pde = new ProdutoServico();
        //pragas encontrada
        StringTokenizer aux = new StringTokenizer(sModel.getSelectedItem().toString(), " ");
        Pragas pg =  p.buscarComID(Integer.parseInt(aux.nextToken()));
        pe.setPragas(pg);
        pe.setQuantidade(Integer.parseInt(pragas));
        pe.setOrdemServico(os);
        pe.armazenar();
        //produto usado
        StringTokenizer aux_p = new StringTokenizer(pModel.getSelectedItem().toString(), " ");
        Produto pdu =  pd.buscarComID(Integer.parseInt(aux_p.nextToken()));
        pde.setOrdemServico(os);
        pde.setProduto(pdu);
        pdu.setQuantidadeEstoque(pdu.getQuantidadeEstoque() - Integer.parseInt(prod));
        pdu.alterar();
        pde.setQuantidade(Integer.parseInt(prod));
        pde.setQuantidade(Integer.parseInt(prod));
        pde.armazenar();
        
        os.alterar();
        atualizarTabelaServico();
        this.desativarBotoesServ();
    }//GEN-LAST:event_btnConcluidoActionPerformed

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        // TODO add your handling code here:
        if(this.jDate.getDate() != null){
            Date pega = jDate.getDate();
            SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
            String d = formato.format(pega);
            String id = tblServico.getModel().getValueAt(linhaTabelaServico, 0).toString();
            OrdemServico os;
            DAOServico dao = new DAOServico();
            os = dao.buscarComID(Integer.parseInt(id));
            os.setData(d);
            os.setStatus("A");
            os.alterar();
            atualizarTabelaServico();
            desativarBotoesServ();
        }
    }//GEN-LAST:event_btnAgendarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnCancelar1;
    private javax.swing.JToggleButton btnConcluido;
    private javax.swing.JToggleButton btnConcluido1;
    private javax.swing.ButtonGroup btnEndeGroup;
    private javax.swing.JToggleButton btnGerarOrdens;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProposta;
    private javax.swing.JTable tblServico;
    // End of variables declaration//GEN-END:variables
}
