/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.view;

import sistema.model.DAOFornecedor;
import sistema.model.DAOProduto;
import sistema.controller.Fornecedor;
import sistema.controller.Produto;
import java.awt.Component;
import java.util.List;
import java.util.StringTokenizer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rickh
 */
public class ProdutoGUI extends javax.swing.JInternalFrame {
    
    private Produto produto;
    
    /**
     * Creates new form CrudCliente
     */
    public ProdutoGUI() {
        initComponents();
        carregarScrollEnd();
        atualizarTabelaProdutos();
        this.desativarBotoes();
        this.btnSave.setEnabled(true);
        this.produto = null;
    }
    
    void carregarScrollEnd(){
        this.cmbFornecedor.removeAllItems();
        DAOFornecedor end = new DAOFornecedor();
        end.listar(this.cmbFornecedor);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        BarraDeBusca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPAtivo = new javax.swing.JTextField();
        txtFabricante = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        spnEstoque = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        cmbFornecedor = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnMerge = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Informações de Endereço");

        jTextField9.setText("jTextField8");

        setPreferredSize(new java.awt.Dimension(1050, 550));

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Produto");

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Princípio Ativo", "Fabricante", "Preço (R$)", "Em Estoque", "Fornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdutos.setName("tblProdutos"); // NOI18N
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblProdutosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdutos);

        BarraDeBusca.setName("barraBusca"); // NOI18N
        BarraDeBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BarraDeBuscaKeyReleased(evt);
            }
        });

        jLabel2.setText("Nome do Produto");

        jLabel5.setText("Nome");

        jLabel6.setText("Princípio Ativo");

        jLabel7.setText("Fabricante");

        txtNome.setName("txtNome"); // NOI18N

        txtPAtivo.setName("txtPAtivo"); // NOI18N

        txtFabricante.setName("txtFabricante"); // NOI18N

        jLabel10.setText("Em Estoque");

        jLabel11.setText("Preço");

        txtPreco.setName("txtPreco"); // NOI18N

        spnEstoque.setName("numEstoque"); // NOI18N

        jLabel12.setText("Fornecedor");

        cmbFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFornecedor.setName("cmbFornecedor"); // NOI18N

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Plus_2190977.png"))); // NOI18N
        btnSave.setText("Adicionar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnMerge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Compose_2190985.png"))); // NOI18N
        btnMerge.setText("Alterar");
        btnMerge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMergeActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Close_2190987.png"))); // NOI18N
        btnDelete.setText("Excluir");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMerge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnMerge)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BarraDeBusca))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(spnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNome)
                                    .addComponent(txtPAtivo)
                                    .addComponent(txtFabricante, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BarraDeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(spnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void limpaCampos(){
        txtNome.setText("");
        txtPAtivo.setText("");
        txtFabricante.setText("");
        spnEstoque.setValue(0);
        txtPreco.setText("");
    }
    
    private boolean verificaCampos(){
        boolean nome = false, rg = false, fabricante = false, preco = false, forn = false;
        if(!txtNome.getText().isEmpty()){
            nome = true;
        }
        if(!txtPAtivo.getText().isEmpty()){
            rg = true;
        }
        if(!txtFabricante.getText().isEmpty()){
            fabricante = true;
        }
        if(!txtPreco.getText().isEmpty()){
            preco = true;
        }
        if(cmbFornecedor.getSelectedIndex() != -1){
            forn = true;
        }
        return nome && rg && preco && fabricante && forn;
    }
    
    private void atualizarTabelaProdutos(){
        limparTabela();
        DAOProduto daoProduto = new DAOProduto();
        DefaultTableModel modelo = (DefaultTableModel) tblProdutos.getModel();
        daoProduto.listar(modelo);
    }
    
    public void limparTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tblProdutos.getModel();
        modelo.setNumRows(0);
        tblProdutos.setModel(modelo);
    }
    
    private void PesquisarProduto(String param){
        DAOProduto daoProduto = new DAOProduto();
        DefaultTableModel modelo = (DefaultTableModel) tblProdutos.getModel();
        daoProduto.listarComLike(param, BarraDeBusca.getText(), modelo);
    }
    
    private void setProduto(int idProduto){
        DAOProduto daoProduto = new DAOProduto();
        this.produto = daoProduto.buscarComID(idProduto);
        StringTokenizer aux;
        txtNome.setText(this.produto.getNome());
        txtPAtivo.setText(this.produto.getPrincipioAtivo());
        txtFabricante.setText(this.produto.getFabricante());
        txtPreco.setText(String.valueOf(this.produto.getPreco()));
        
        SpinnerNumberModel spn = new SpinnerNumberModel((int)this.produto.getQuantidadeEstoque(), -1000, 1000, 1);
        spnEstoque.setModel(spn);
        
        int idF = this.produto.getFornecedor().getIdFornecedor();
        for(int i = 0; i < cmbFornecedor.getItemCount(); i++){
            aux = new StringTokenizer(cmbFornecedor.getItemAt(i), " ");
            int idScroll = Integer.parseInt(aux.nextToken());
            if(idScroll == idF){
                cmbFornecedor.setSelectedIndex(i);
                break;
            }
        }
    }
    
    
    
    private void ativarBotoes(){
        this.btnDelete.setEnabled(true);
        this.btnMerge.setEnabled(true);
        this.btnSave.setEnabled(true);
    }
    
    private void desativarBotoes(){
        this.btnDelete.setEnabled(false);
        this.btnMerge.setEnabled(false);
        this.btnSave.setEnabled(false);
    }
    
    private Produto criarProduto(){
        Produto p = new Produto();
        DAOFornecedor f = new DAOFornecedor();
        try {
            p.setNome(txtNome.getText());
            p.setFabricante(txtFabricante.getText());
            p.setPrincipioAtivo(txtPAtivo.getText());
            p.setPreco(Float.valueOf(txtPreco.getText()));
            p.setQuantidadeEstoque((Integer)spnEstoque.getValue());
            StringTokenizer aux = new StringTokenizer(cmbFornecedor.getSelectedItem().toString(), " ");
            p.setFornecedor(f.buscarComID(Integer.parseInt(aux.nextToken())));
        } catch (Exception e) {
        
        }
        
        
        return p;
    }
    
    private void btnMergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMergeActionPerformed
    if(verificaCampos()){
            DAOProduto daoProduto = new DAOProduto();
        
            Produto p = criarProduto();
            p.setIdProduto(produto.getIdProduto());
            System.out.println(p.getNome());
            daoProduto.alterar(p);
            
            atualizarTabelaProdutos();
            limpaCampos();
            this.produto = null;
            this.btnDelete.setEnabled(false);
            this.btnMerge.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(null, "Campo(s) obrigatório(s) em branco.");
        }
    }//GEN-LAST:event_btnMergeActionPerformed

    private void tblProdutosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMousePressed
        // TODO add your handling code here:
        int linhaTabelaProduto = tblProdutos.getSelectedRow();
        String id = tblProdutos.getModel().getValueAt(linhaTabelaProduto, 0).toString();
        setProduto(Integer.parseInt(id));
        this.ativarBotoes();
    }//GEN-LAST:event_tblProdutosMousePressed

    private void BarraDeBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BarraDeBuscaKeyReleased
        limparTabela();
        PesquisarProduto("nome");
    }//GEN-LAST:event_BarraDeBuscaKeyReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DAOProduto daoProduto = new DAOProduto();
        daoProduto.excluir(this.produto.getIdProduto());
        this.limparTabela();
        
        
        atualizarTabelaProdutos();
        this.produto = null;
        limpaCampos();
        this.btnDelete.setEnabled(false);
        this.btnMerge.setEnabled(false);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(verificaCampos()){
            Produto produto = criarProduto();
            DAOProduto daoProduto = new DAOProduto();
            daoProduto.armazenar(produto);
            
            atualizarTabelaProdutos();
            this.produto = null;
            limpaCampos();
            this.btnDelete.setEnabled(false);
            this.btnMerge.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(null, "Campo(s) obrigatório(s) em branco.");
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    
    private class ComboModelFornecedor extends DefaultComboBoxModel { 
       private List<Fornecedor> fornecedores = null;  
       public ComboModelFornecedor(List<Fornecedor> fornecedores) {  
          this.fornecedores = fornecedores;  
       }  
       @Override  
       public void addElement(Object anObject) {  
          this.fornecedores.add((Fornecedor)anObject);  
          //notifica o combo que o modelo foi alterado.  
          this.fireIntervalAdded(this, 0, 0);  
       }  
        @Override
       public Object getElementAt(int index) {  
          return this.fornecedores.get(index);  
       }
        @Override
       public Object getSelectedItem() {  
          return super.getSelectedItem();  
       }
        @Override
        public void setSelectedItem(Object anObject) {
            if(anObject != null)
                super.setSelectedItem(anObject);
        }
       
        @Override
       public int getSize() {  
          return this.fornecedores.size();  
       }
    }
    
    private class FornecedorCellRenderer extends DefaultListCellRenderer{
        public Component getListCellRendererComponent(JList<? extends Object> list,
            Object value, int index, boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (value instanceof Fornecedor) {
                setText(((Fornecedor) value).getNome());
            }
            return this;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraDeBusca;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMerge;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JSpinner spnEstoque;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPAtivo;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables

}