/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.view;

import sistema.model.DAOCliente;
import sistema.model.DAOProposta;
import sistema.controller.Cliente;
import sistema.controller.Proposta;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rickh
 */
public class PropostaGUI extends javax.swing.JInternalFrame {
    private Proposta proposta;
    /**
     * Creates new form CrudCliente
     */
    public PropostaGUI() {
        initComponents();
        carregarScrollEnd();
        atualizarTabelaProposta();
        this.desativarBotoes();
        this.btnSave.setEnabled(true);
        this.proposta = null;
    }
    
    void carregarScrollEnd(){
        this.cmbTipo.removeAllItems();
        this.cmbTipo.addItem("Esporádico");
        this.cmbTipo.addItem("Periódico");
    }
    
    private boolean verificaCampos(){
        boolean cpf = false, descrip = false, orcamento = false;
        if(!txtCPF.getText().isEmpty()){
            cpf = true;
        }
        if(!txtDescrip.getText().isEmpty()){
            descrip= true;
        }
        if(!txtOrcamento.getText().isEmpty()){
            orcamento = true;
        }
        return cpf && descrip && orcamento;
    }
    
    private void limpaCampos(){
        txtCPF.setText("");
        txtDescrip.setText("");
        txtOrcamento.setText("");
    }

    private void inicializarCombo(){
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        dcm.addElement("Esporádico");
        dcm.addElement("Periódico");
        cmbTipo.setModel(dcm);
    }
    
    private void atualizarTabelaProposta(){
        limparTabela();
        DAOProposta daoProposta = new DAOProposta();
        DefaultTableModel modelo = (DefaultTableModel) tblProposta.getModel();
        daoProposta.listar(modelo);
    }
    
    public void limparTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tblProposta.getModel();
        modelo.setNumRows(0);
        tblProposta.setModel(modelo);
    }
    
    private void PesquisarProposta(String param){
        DAOProposta daoProposta = new DAOProposta();
        DefaultTableModel modelo = (DefaultTableModel) tblProposta.getModel();
        daoProposta.listarComJoinCliente(param, BarraDeBusca.getText(), modelo);
    }
    
    private void setProposta(int idProposta){
        DAOProposta daoProposta = new DAOProposta();
        this.proposta = daoProposta.buscarComID(idProposta);

        txtCPF.setText(this.proposta.getCliente().getCadastro().getCpf());
        txtDescrip.setText(this.proposta.getDescricao());
        txtOrcamento.setText(String.valueOf(this.proposta.getOrcamento()));
        
        for(int i = 0; i<cmbTipo.getModel().getSize(); i++){
            if(cmbTipo.getModel().getElementAt(i).equals(this.proposta.getTipoServico())){
                cmbTipo.setSelectedIndex(i);
                break;
            }
        }
    }
    
    private void ativarBotoes(){
        this.btnDelete.setEnabled(true);
        this.btnMerge.setEnabled(true);
        this.btnSave.setEnabled(true);
        this.btnDeliberar.setEnabled(true);
        this.btnRecusar.setEnabled(true);
    }
    
    private void desativarBotoes(){
        this.btnDelete.setEnabled(false);
        this.btnMerge.setEnabled(false);
        this.btnSave.setEnabled(false);
        this.btnDeliberar.setEnabled(false);
        this.btnRecusar.setEnabled(false);
    }
    
    private void criarProposta(){
        char [] array;
        this.proposta = new Proposta();
        //proposta = new Proposta();
        DAOCliente daoCliente = new DAOCliente();
        try {
            proposta.setCliente((Cliente)daoCliente.buscarComCPF(txtCPF.getText()));
            proposta.setDescricao(txtDescrip.getText());
            proposta.setOrcamento(Float.parseFloat(txtOrcamento.getText()));
            array = ((String)cmbTipo.getSelectedItem()).toCharArray();
            if(array[0] == 'P'){
                proposta.setTipoServico("P");
            }else{
                proposta.setTipoServico("I");
            }
            proposta.setStatus("P");
        } catch (Exception e) {
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProposta = new javax.swing.JTable();
        BarraDeBusca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnMerge = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtOrcamento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDescrip = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnDeliberar = new javax.swing.JButton();
        btnRecusar = new javax.swing.JButton();

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Informações de Endereço");

        jTextField9.setText("jTextField8");

        setPreferredSize(new java.awt.Dimension(1050, 550));

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Proposta");

        tblProposta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome Cliente", "Tipo de Serviço", "Descrição", "Orçamento", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProposta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPropostaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblProposta);

        BarraDeBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BarraDeBuscaKeyReleased(evt);
            }
        });

        jLabel2.setText("Nome Cliente");

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Plus_2190977.png"))); // NOI18N
        btnSave.setText("Adicionar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnMerge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Compose_2190985.png"))); // NOI18N
        btnMerge.setText("Alterar");
        btnMerge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMergeActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Close_2190987.png"))); // NOI18N
        btnDelete.setText("Excluir");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMerge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnMerge)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("CPF Cliente");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Esporádico", "Periódico" }));
        cmbTipo.setName("cmbServiço"); // NOI18N

        jLabel6.setText("Tipo de Serviço");

        jLabel7.setText("Descrição");

        jLabel11.setText("Orçamento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCPF)
                    .addComponent(cmbTipo, 0, 246, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtDescrip))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Deliberar Proposta");

        btnDeliberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Checkmark_2190986.png"))); // NOI18N
        btnDeliberar.setText("Deliberar");
        btnDeliberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliberarActionPerformed(evt);
            }
        });

        btnRecusar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Close_2190987.png"))); // NOI18N
        btnRecusar.setText("Recusar");
        btnRecusar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecusarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BarraDeBusca))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRecusar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeliberar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BarraDeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeliberar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRecusar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMergeActionPerformed
        if(verificaCampos()){
            char [] array;
            //proposta = new Proposta();
            DAOCliente daoCliente = new DAOCliente();
            DAOProposta daoProposta = new DAOProposta();
            proposta.setCliente((Cliente)daoCliente.buscarComCPF(txtCPF.getText()));
            proposta.setDescricao(txtDescrip.getText());
            proposta.setOrcamento(Float.parseFloat(txtOrcamento.getText()));
            array = ((String)cmbTipo.getSelectedItem()).toCharArray();
            if(array[0] == 'P'){
                proposta.setTipoServico("P");
            }else{
                proposta.setTipoServico("I");
            }
            proposta.setStatus("P");
            daoProposta.alterar(this.proposta);
            
            atualizarTabelaProposta();
            limpaCampos();
            this.proposta = null;
            this.btnDelete.setEnabled(false);
            this.btnMerge.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(null, "Campo(s) obrigatório(s) em branco.");
        }
    }//GEN-LAST:event_btnMergeActionPerformed

    private void tblPropostaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPropostaMousePressed
        int linhaTabelaProposta = tblProposta.getSelectedRow();
        this.proposta = new Proposta();
        String id = tblProposta.getModel().getValueAt(linhaTabelaProposta, 0).toString();
        setProposta(Integer.parseInt(id));
        this.proposta.setIdProposta(Integer.parseInt(id));
        
        this.ativarBotoes();
    }//GEN-LAST:event_tblPropostaMousePressed

    private void BarraDeBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BarraDeBuscaKeyReleased
        limparTabela();
        PesquisarProposta("nome");      
    }//GEN-LAST:event_BarraDeBuscaKeyReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DAOProposta daoProposta = new DAOProposta();
        daoProposta.excluir(this.proposta.getIdProposta());
        this.limparTabela();
        atualizarTabelaProposta();
        this.proposta = null;
        limpaCampos();
        this.btnDelete.setEnabled(false);
        this.btnMerge.setEnabled(false);
        this.btnDeliberar.setEnabled(false);
        this.btnRecusar.setEnabled(false);
        this.btnDelete.setEnabled(false);
        this.btnMerge.setEnabled(false);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(verificaCampos()){
            criarProposta();
            proposta.armazenar();
            atualizarTabelaProposta();
            this.proposta = null;
            limpaCampos();
            desativarBotoes();
            this.btnSave.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null, "Campo(s) obrigatório(s) em branco.");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeliberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliberarActionPerformed
        // TODO add your handling code here:
        this.proposta.setStatus("A");
        this.proposta.alterar();
            
        atualizarTabelaProposta();
        JOptionPane.showMessageDialog(null, "Proposta alterada com sucesso");
        limpaCampos();
        this.proposta = null;
        desativarBotoes();
        this.btnSave.setEnabled(true);
    }//GEN-LAST:event_btnDeliberarActionPerformed

    private void btnRecusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecusarActionPerformed
        // TODO add your handling code here:
        this.proposta.setStatus("R");
        this.proposta.alterar();
            
        atualizarTabelaProposta();
        limpaCampos();
        this.proposta = null;
        this.btnDelete.setEnabled(false);
        this.btnMerge.setEnabled(false);
    }//GEN-LAST:event_btnRecusarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraDeBusca;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeliberar;
    private javax.swing.JButton btnMerge;
    private javax.swing.JButton btnRecusar;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable tblProposta;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtDescrip;
    private javax.swing.JTextField txtOrcamento;
    // End of variables declaration//GEN-END:variables
}
